version: '3.8'


services:
  oracle-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tordb1-container
    ports:
      - "1521:1521"
      - "5500:5500"
    env_file:
      - .env
    environment:
      ORACLE_SID: ${ORACLE_SID}
      ORACLE_PDB: ${ORACLE_PDB}
      ORACLE_PWD: ${ORACLE_PWD}
      ORACLE_CHARACTERSET: ${ORACLE_CHARACTERSET}
    volumes:
     - oracle-data:/opt/oracle/oradata
volumes:
  oracle-data:
